### Pandas Dataframe

**Q1. Creating a DataFrame**
**Create a Pandas DataFrame using a Python dictionary with the following columns:**
- Product
- Region
- Sales
- Quantity

**Add at least 5 rows of sample data and display the DataFrame.**

In [65]:
import pandas as pd

DataFrame = pd.DataFrame({'Product': [ 'Keyboard', 'Monitor', 'Phone', 'Tablet', 'Laptop'], 
                          'Region': ['East', 'West', 'North', 'West', 'South'], 
                          'Sales': [1200, 8000, 17000, 79000, 5100], ''
                          'Quantity':[4, 2, 1, 2, 1]})
DataFrame.head()

    Product Region  Sales  Quantity
0  Keyboard   East   1200         4
1   Monitor   West   8000         2
2     Phone  North  17000         1
3    Tablet   West  79000         2
4    Laptop  South   5100         1

**Q2. Data Inspection** <br>
Perform the following inspection tasks:
- Display the first 5 rows of the dataset.
- Display the last 5 rows.
- Show the structure of the dataset using info().
- Display the shape of the dataset.

In [66]:
df = pd.read_csv('Retail_dataset.csv')
print('\n\n The first 5 rows of the dataset: ')
print(df.head(5)) 
print('\n\n The last 5 rows: ')
print(df.tail(5))
print('\n\n Structure of the dataset: ')
print(df.info())
print(f'\n Shape of the dataset: {df.shape}\n')

 The first 5 rows of the dataset:
   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4


 The last 5 rows:
    Order_ID Customer   Product Region  Sales  Quantity
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   West    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2


 Structure of the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB
None

 Shape of the dataset: (90, 6)

**Q3. Column Selection** <br> 
Select and display only the following columns:
- Product
- Region
- Sales

In [67]:
df[['Product', 'Region', 'Sales']]

     Product Region  Sales
0     Laptop   West   1056
1     Tablet  South    904
2     Laptop  South   1597
3   Keyboard  North    777
4      Phone  South   2028
..       ...    ...    ...
85    Laptop   East   1330
86  Keyboard   West    741
87   Monitor   East    875
88    Tablet  North   2213
89    Laptop  South   1270

[90 rows x 3 columns]

**Q4. Indexing using .loc** <br> 
Using .loc, perform the following:
- Display the row with index 10.
- Display the Sales value of the row with index 20

In [68]:
print(f'The row with index 10: {df.loc[10]}')
print(f'\nThe Sales value of the row with index20: {df.loc[20, 'Sales']}')

The row with index 10: Order_ID       1011
Customer        Raj
Product     Monitor
Region        North
Sales          1693
Quantity          6
Name: 10, dtype: object

The Sales value of the row with index20: 1021

**Q5. Indexing using .iloc** <br> 
Using .iloc, display:
- The first 6 rows and first 4 columns.
- The Sales value from the 3rd row.

In [69]:
print(f"First 6 rows and 4 columns: \n {df.iloc[0:6, 0:4]}\n")

print(f"\nSales value from the 3rd row:\n {df['Sales'].iloc[2:]}")

First 6 rows and 4 columns:
    Order_ID Customer   Product Region
0      1001    Sneha    Laptop   West
1      1002     Neha    Tablet  South
2      1003    Meera    Laptop  South
3      1004    Rohan  Keyboard  North
4      1005    Priya     Phone  South
5      1006    Rahul    Tablet   West


Sales value from the 3rd row:
 2     1597
3      777
4     2028
5      638
6     1004
      ...
85    1330
86     741
87     875
88    2213
89    1270
Name: Sales, Length: 88, dtype: int64

**Q6. Row Slicing** <br>
Display:
- The first 10 rows of the dataset.
- Rows 15 to 25.

In [70]:
print(f'The first 10 rows of the dataset: \n {df.iloc[0:10]}\n')

print(f'\nRows 15 to 25:\n {df.iloc[15:26]}\n')

The first 10 rows of the dataset:
    Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4
5      1006    Rahul    Tablet   West    638         2
6      1007     Amit   Monitor  South   1004         7
7      1008    Sneha   Monitor   East   1269         8
8      1009    Priya     Phone  North    827         8
9      1010     Amit     Phone   West   1998         4


Rows 15 to 25:
     Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

**Q7. Filtering Data** <br>
Filter the dataset to display:
- Rows where Region = "East".
- Rows where Sales > 1500.

In [71]:
df[(df['Region']=='East') & (df['Sales'] > 1500)]

    Order_ID Customer   Product Region  Sales  Quantity
16      1017     Neha    Laptop   East   2015         2
31      1032     Amit    Laptop   East   2226         6
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
44      1045    Priya     Phone   East   1875         4
52      1053    Rahul    Laptop   East   2276         1
66      1067    Rahul    Tablet   East   1875         6
71      1072    Anita  Keyboard   East   1702         3
79      1080    Pooja    Tablet   East   1829         2
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5

**Q8. Multiple Condition Filtering** <br>
Display rows where:
- Region is West
- Sales is greater than 1200

In [72]:
df[(df['Region']=='West') & (df['Sales'] > 1200)]

    Order_ID Customer   Product Region  Sales  Quantity
9       1010     Amit     Phone   West   1998         4
19      1020     Neha    Laptop   West   1503         6
24      1025    Meera   Monitor   West   1926         6
29      1030    Rohan   Monitor   West   1932         5
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
49      1050    Karan   Monitor   West   2034         7
55      1056    Rahul    Laptop   West   1481         1
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
63      1064    Pooja  Keyboard   West   2310         5
68      1069    Priya    Laptop   West   1422         6
69      1070    Rahul    Tablet   West   2134         5
73      1074    Meera  Keyboard   West   1429         7
83      1084    Rohan    Laptop   West   1204         5
84      1085     Neha   Monitor   West   1339         7

**Q9. Descriptive Statistics** <br>
Generate summary statistics using: <br>
describe() <br>
From the result identify: 
- Mean sales value
- Maximum quantity sold
- Minimum sales value

In [73]:
print(f'Mean sales value: {df['Sales'].mean()}')
print(f'Maximum quantity sold: {max(df['Quantity'])}')
print(f'Minimum sales value: {min(df['Sales'])}')

df[['Sales','Quantity']].describe()

Mean sales value: 1406.888888888889
Maximum quantity sold: 8
Minimum sales value: 515

             Sales   Quantity
count    90.000000  90.000000
mean   1406.888889   4.700000
std     531.748302   2.179836
min     515.000000   1.000000
25%     890.500000   3.000000
50%    1402.000000   5.000000
75%    1857.250000   7.000000
max    2455.000000   8.000000

**Q10. Aggregation Analysis** <br>
Using the Sales column, calculate:
- Total sales
- Average sales
- Maximum sales
- Minimum sales

In [74]:
print(f'Total sales: {df['Sales'].mean()}')
print(f'Average sales: {df['Sales'].mean()}')
print(f'Maximum sales: {max(df['Sales'])}')
print(f'Minimum sales: {min(df['Sales'])}')

Total sales: 1406.888888888889
Average sales: 1406.888888888889
Maximum sales: 2455
Minimum sales: 515